version: '3.8'

services:
  invoker:
    build:
      context: ./app/services/invoker
    ports:
      - "5001:5001"
    environment:
      FLASK_APP=invoker.py
      FLASK_RUN_HOST=0.0.0.0
      REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true